<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner border-gray-200 dark:bg-gray-900">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Transforme notas fiscais em indicadores: registre chegadas agora.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Eficiência fiscal: equipe pronta para escrituração e entrada no estoque.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Transparência total: informe a matriz sobre cada nota na fazenda.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form action="/authenticate" method="post">
			<div class="row">
				<div class="col">
					<input type="text" name="email" class="form-control" placeholder="E-mail">
				</div>
				<div class="col">
					<input type="password" name="password" class="form-control" placeholder="Senha">
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
			<?php if($this->view->login == 'error') { ?>
				<div class="row">
					<div class="col">
						<span class="text text-danger">*Email e/ou senha invalido(s)</span>
					</div>
				</div>
			<?php } ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/logo_walker.jpg" />
				<h1 class="title"></h1>

				<h2 class="mt-5 subtitle"></h2>
				<a href="/singUp" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>


    </div>

  </div>
</div>