<html>
	<head>
		<meta charset="utf-8" />
		<title>Registro de Chegada</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	
		<link rel="stylesheet" type="text/css" href="/css/style.css">
		
	</head>

	<body class="antialiased">
		<!-- Menu Top Fixed -->
		<nav class="navbar navbar-expand-lg menu">
			<div class="container">
			<div class="navbar-nav">
				<!-- <a class="menuItem" href="/timeline">
					Home
				</a>

				<a class="menuItem" href="/logOut">
					Sair
				</a> -->
					<img src="/img/logo_walker-1.jpg" class="menuIco" />
			</div>
			</div>
		</nav>
		<div class="pt-1 mt-5"></div>
		<div class="container-fluid mt-5">
			<div class="row pt-2">
				
				<!-- Perfil do Usuário -->
				<div class="col-md-auto"->

					<div class="perfil">
						<div class="perfilTopo" style="display:block; display: -webkit-flex; justify-content: center; align-items: center;">
							<div class="col mb-2">
								<a class="ContainerPerfilTopo" href="/timeline">
									<img class="perfilimg" src="/img/logo_walker.ico" class="img-fluid" alt="..." style="border-radius: 100%; max-width: 6rem; max-height: 6rem; width:auto, height:auto;margin-top: 6rem">
								</a>
							</div>
						</div>

						<div class="perfilPainel">

							<div class="row mt-5 mb-2">
							
								<div class="col mb-2">
									<span class="perfilPainelNome"><?= $this->view->info_user['name']?></span>
								</div>
							</div>

							<div class="row mb-2">

								<div class="col">
									<span class="perfilPainelItem">Postados</span><br />
									<span class="perfilPainelItemValor text-success"><?= $this->view->totalInvoices['totalInvoices']?></span>
								</div>

								<div class="col">
									<span class="perfilPainelItem">Lançados</span><br />
									<span class="perfilPainelItemValor text-success"><?= $this->view->totalNotPedingInvoices['totalNotPedingInvoices']?></span>
								</div>

								<div class="col">
									<span class="perfilPainelItem">Pendentes</span><br />
									<span class="perfilPainelItemValor text-success"><?= ( $this->view->totalInvoices['totalInvoices'])-($this->view->totalNotPedingInvoices['totalNotPedingInvoices'])?></span>
								</div>

							</div>

						</div>
					</div>

				</div>
				<?= $this->content() ?>
				<div class="col-md">
					<div class="quemSeguir">
						<span class="quemSeguirTitulo">Links</span><br />
						<hr />
						<a class="menuItem text-success" href="/timeline">Home</a>
					
						
						<hr />
						<a class="menuItem text-success" href="/logOut">Sair</a>
						
						
						<hr />
						<div class="c"><a class="menuItem text-success" href="/home" class="quemSeguirTxt">Procurar</a></div>
					</div>
				</div>
			</div>
		</div>
		
	</body>

</html>